### ISSUE TITLE
"'NoneType' object is not subscriptable" in upload_file

### ISSUE THREAD

**Issue by readmanisme** [panos-stavrianos/py-directus#4]
Directus version : 10.9.3
py-directus version : 0.0.28
The code:
`
result=await directus.upload_file(to_upload=file_str,folder="test_folder")
`
Error:"'NoneType' object is not subscriptable"
Reason: In the source code:
`
 if folder:
            folder_id = \
            (await self.collection('directus_folders').fields("id").filter(name="documents").read()).item[
                    "id"]
`
The '**name="documents**"' should be replaced with '**name=folder**'.

**Comment by MultiJohnen** [comment]
Good day @readmanisme,
this line was changed in [this](https://github.com/panos-stavrianos/py-directus/commit/f409a7bee4ff2d34fd7658acee8203f01c0877e9) commit.
Please, make sure that you really are on the 0.0.28 version of the library.
I leave the issue open for now to make additional checks.
